name: Mirror Codeberg Repo (LFS)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git LFS
        run: |
          git lfs install

      - name: Clone Codeberg repo
        run: |
          git clone https://codeberg.org/vherawidatama/android_vendor_xiaomi_zorn.git repo

      - name: Setup git identity
        run: |
          cd repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Track large files with LFS
        run: |
          cd repo
          git lfs track "*.so" "*.img" "*.bin"
          git add .gitattributes
          git commit -m "Track large files with Git LFS" || true

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo
          git remote add github https://x-access-token:${GITHUB_TOKEN}@github.com/zorn-trees/android_vendor_xiaomi_zorn.git
          git push --force github master
